### ISSUE TITLE
Create a "guesser" tool to identify possible first guesses of SS variables

### ISSUE THREAD

**Issue by SeaCelo** [EAPD-DRB/OG-ZAF#23]
In creating the baseline model it would be helpful to know which values for the steady state variables give valid solutions. A script could loop through the baseline model using different guesses and report back on the ones that did not fail. The loop should only include the validity check and does not need to run the entire solution to speed up the loop.

**Comment by rickecon** [comment]
I opened an issue on this topic ([Issue #831](https://github.com/PSLmodels/OG-Core/issues/831)) last Friday to be incorporated into `OG-Core`. That would make this available to any country calibration that uses `OG-Core`.

**Comment by rickecon** [comment]
This issue is resolved by [PR #836](https://github.com/PSLmodels/OG-Core/pull/836) in the OG-Core repository. The file `SS.py` now includes a list of adjustment/deviation factors for the `initial_guess_r_SS` and `initial_guess_TR_SS` in [lines 1106-1147](https://github.com/PSLmodels/OG-Core/blob/master/ogcore/SS.py#L1106) and [line 1165](https://github.com/PSLmodels/OG-Core/blob/master/ogcore/SS.py#L1165) and [line 1175](https://github.com/PSLmodels/OG-Core/blob/master/ogcore/SS.py#L1175).

cc: @SeaCelo, @sarvonz
